ASSET_FEES = {
    "AMUNDI EURO GOVERNMENT BOND 1-3Y UCITS ETF ACC": 0.17,
    "AMUNDI EURO GOVERNMENT BOND 3-5Y UCITS ETF ACC": 0.17,
    "AMUNDI EURO GOVERNMENT BOND 7-10Y UCITS ETF ACC": 0.17,
    "AMUNDI EURO GOVERNMENT BOND 10-15Y UCITS ETF ACC": 0.17,
    "AMUNDI US TREASURY BOND 7-10Y UCITS ETF EUR HEDGED ACC": 0.05,
    "AMUNDI US TREASURY BOND 7-10Y UCITS ETF ACC USD": 0.05,
    "AMUNDI GLOBAL AGGREGATE BOND UCITS ETF DR (D)": 0.10,
}

TRADING_DAYS = 252